require: sudo

services:
  - docker

before_install:
  - docker build -t marcodd23/docker-react -f Dockerfile.dev .

script:
  - docker run marcodd23/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-106290293891'
  bucket_path: 'docker-react'
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
  on:
    branch: master
